version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pw
      - MYSQL_PASSWORD=db_pw
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=test_db